### ISSUE TITLE
rhd-frontend should build a distribution of the assets to be used by Drupal

### ISSUE THREAD

**Issue by robpblake** [redhat-developer/rhd-frontend#395]
At the minute the `Dockerfile` for Drupal has a number of commands to move assets from the `dist` directory of the `rhd-frontend` component around into the correct location. For example:

https://github.com/redhat-developer/developers.redhat.com/blob/master/_docker/drupal/Dockerfile.mp#L36-L56

Instead, `rhd-frontend` should support building it's distributable assets into a form that can be consumed directly by Drupal. This distribution should be produced by a single command. For example `npm run build-drupal-distribution`. Once this command has run, the `dist` directory of the `rhd-frontend` component should be in a state that can be consumed directly by Drupal.

How it is to be consumed by Drupal is then a choice of Drupal. We can either include it directly on the Drupal filesystem via our current mechanism, or alternatively we can upload the `dist` directory to a CDN and have Drupal consume it from there.

**Comment by jordanpagewhite** [comment]
Hey @robpblake Do you feel that this issue is resolved and/or no longer relevant given the current state of rhd-frontend in the Drupal repo?

**Comment by robpblake** [comment]
@jordanpagewhite Not resolved and it's still relevant. 

Essentially the `rhd-frontend` package.json should offer a single command e.g: `npm run build-drupal-dist` which would put all assets required by Drupal into the `dist` directory in the correct structure e.g:

* `dist/js/rhd-old.min.js`
* `dist/css/rhd-old.min.css`
* `dist/fonts`
* ...

Then we can update the `Dockerfile` for Drupal to simply:

`cp -r rhd-frontend/dist themes/custom/rhdp2/`

as an overlay. This would remove all of the `mv` and `rm` commands for building the theme and the only thing that needs to change when a new asset is produced by the `rhd-frontend` is package.json.
